name: publish to dockerhub

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:

jobs:
  build:
    name: publish to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build (and publish) main image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/fopina/proxybroker:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
